config:
  seed: 42
  batch_size: 8
  inference_batch_size: 8
  inference_artifacts_per_batch_per_epoch: 32
  validation_split: 0.2
  learning_rate: 0.0001
  epochs: 128
  window: 1024
  inference_window: 1024
  stride: 256
  step_freq: 64
  test_size: 0.1
  mesh_x_div: 1
  loss_fn: 1
  features_list: [64, 64, 32, 32]
  sine_window: 63
  cropping: 1
