config:
  seed: 42
  batch_size: 8
  inference_batch_size: 8
  inference_artifacts_per_batch_per_epoch: 32
  validation_split: 0.2
  learning_rate: 0.0001
  epochs: 128
  window: 512
  inference_window: 512
  stride: 256
  step_freq: 64
  test_size: 0.1
  mesh_x_div: 1
  loss_fn: 1
  features_list: [64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64, 64]
  sine_window: 31
  do_last_skip: true
  cropping: 1
  sines_per_window: 64
