config:
  seed: 42
  batch_size: 8
  inference_batch_size: 8
  inference_artifacts_per_batch_per_epoch: 32
  validation_split: 0.2
  learning_rate: 0.0001
  epochs: 128
  window: 2048
  inference_window: 2048
  stride: 256
  step_freq: 64
  test_size: 0.1
  mesh_x_div: 1
  loss_fn: 1
  dense_across_stack: 2
  dense_across_stack_activation: 5
  use_previous_derivative: false
  #
  seed_sine: 531
  features: 1024
  skip: False
  levels: 32
  end_features: 64
  end_levels: 32
